[resource]
    PrivateKey = $(wg genkey)
    Address = 192.168.29.106

    [gateway]
    PublicKey = 8NyVDL+Qtqqiy7VI8EMxe2Q5+gUHVTaJ3XGmHpN/sgc=
    AllowedIPs = "0.0.0.0/32"
    port = 51820
    public_ip = f"127.0.0.1:51820"
    